-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE IF NOT EXISTS "goose_db_version" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "goose_db_version_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"version_id" bigint NOT NULL,
	"is_applied" boolean NOT NULL,
	"tstamp" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "vessels" (
	"id" uuid PRIMARY KEY NOT NULL,
	"imo" text NOT NULL,
	"name" text NOT NULL,
	"type" text NOT NULL,
	"groups" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "vessels_imo_key" UNIQUE("imo")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "cadence_rules" (
	"scope_type" text NOT NULL,
	"vessel_id" uuid,
	"group_tag" text,
	"min_report_interval_hours" double precision NOT NULL,
	"max_gap_hours" double precision NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "regulatory_profile_assignments" (
	"scope_type" text NOT NULL,
	"vessel_id" uuid,
	"group_tag" text,
	"profiles" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "users" (
	"id" uuid PRIMARY KEY NOT NULL,
	"username" text NOT NULL,
	"password_hash" text NOT NULL,
	"roles" jsonb NOT NULL,
	"must_change_password" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "users_username_key" UNIQUE("username")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "schema_versions" (
	"id" uuid PRIMARY KEY NOT NULL,
	"schema_name" text NOT NULL,
	"version" text NOT NULL,
	"source" text NOT NULL,
	"content" "bytea" NOT NULL,
	"published_at" timestamp with time zone NOT NULL,
	"published_by" text NOT NULL,
	"cursor" bigint GENERATED ALWAYS AS IDENTITY (sequence name "schema_versions_cursor_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	CONSTRAINT "schema_versions_schema_name_version_key" UNIQUE("schema_name","version")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "enrollments" (
	"vessel_id" uuid PRIMARY KEY NOT NULL,
	"state" text NOT NULL,
	"code_hash" text DEFAULT '' NOT NULL,
	"initial_master_username" text NOT NULL,
	"initial_master_password_hash" text NOT NULL,
	"issued_at" timestamp with time zone NOT NULL,
	"revoked_at" timestamp with time zone,
	"updated_at" timestamp with time zone NOT NULL,
	"dr_public_key" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "rule_severity_assignments" (
	"scope_type" text NOT NULL,
	"vessel_id" uuid,
	"group_tag" text,
	"severities" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "config_bundles" (
	"id" uuid PRIMARY KEY NOT NULL,
	"label" text DEFAULT '' NOT NULL,
	"schema_versions" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"field_policies" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"regulatory_profiles" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"cadence_rules" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"rule_severities" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"default_role_names" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"published_at" timestamp with time zone NOT NULL,
	"published_by" text NOT NULL,
	"cursor" bigint GENERATED ALWAYS AS IDENTITY (sequence name "config_bundles_cursor_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "bundle_assignments" (
	"scope_type" text NOT NULL,
	"vessel_id" uuid,
	"group_tag" text,
	"bundle_id" uuid NOT NULL,
	"assigned_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "vessel_credentials" (
	"vessel_id" uuid PRIMARY KEY NOT NULL,
	"token_hash" text NOT NULL,
	"token_lookup_hash" text NOT NULL,
	"issued_at" timestamp with time zone NOT NULL,
	"revoked_at" timestamp with time zone,
	"last_used_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "vessel_sync_status" (
	"vessel_id" uuid PRIMARY KEY NOT NULL,
	"app_version" text DEFAULT '' NOT NULL,
	"last_seen_at" timestamp with time zone NOT NULL,
	"applied_bundle_id" text DEFAULT '' NOT NULL,
	"applied_bundle_version" bigint DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "report_audit_events" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "report_audit_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"vessel_id" uuid NOT NULL,
	"report_id" text NOT NULL,
	"version_no" integer NOT NULL,
	"event_type" text NOT NULL,
	"actor" text DEFAULT '' NOT NULL,
	"occurred_at" timestamp with time zone NOT NULL,
	"detail" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"received_at" timestamp with time zone NOT NULL,
	"origin" text DEFAULT 'vessel' NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "invalidation_notices" (
	"seq" bigserial PRIMARY KEY NOT NULL,
	"vessel_id" uuid NOT NULL,
	"report_id" text NOT NULL,
	"version_no" integer NOT NULL,
	"broken_rules" jsonb NOT NULL,
	"computed_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "attachment_uploads" (
	"content_hash" text PRIMARY KEY NOT NULL,
	"total_size" bigint NOT NULL,
	"chunk_size" integer NOT NULL,
	"content_type" text DEFAULT '' NOT NULL,
	"started_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "chat_messages" (
	"id" text PRIMARY KEY NOT NULL,
	"vessel_id" uuid NOT NULL,
	"report_id" text NOT NULL,
	"sender" text NOT NULL,
	"body" text NOT NULL,
	"sent_at" timestamp with time zone NOT NULL,
	"direction" text NOT NULL,
	"seq" bigserial NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "remarks" (
	"id" text PRIMARY KEY NOT NULL,
	"remark_set_id" text NOT NULL,
	"vessel_id" uuid NOT NULL,
	"report_id" text NOT NULL,
	"version_no" integer NOT NULL,
	"field_name" text NOT NULL,
	"body" text NOT NULL,
	"author" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"resolved" boolean DEFAULT false NOT NULL,
	"resolved_at" timestamp with time zone,
	"seq" bigserial NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "report_attachments" (
	"id" text PRIMARY KEY NOT NULL,
	"vessel_id" uuid NOT NULL,
	"report_id" text NOT NULL,
	"version_no" integer NOT NULL,
	"field_name" text NOT NULL,
	"filename" text NOT NULL,
	"content_type" text NOT NULL,
	"content_hash" text NOT NULL,
	"size_bytes" bigint NOT NULL,
	"received_at" timestamp with time zone NOT NULL,
	CONSTRAINT "report_attachments_vessel_id_report_id_version_no_content_h_key" UNIQUE("vessel_id","report_id","version_no","content_hash")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "field_policy_assignments" (
	"scope_type" text NOT NULL,
	"vessel_id" uuid,
	"group_tag" text,
	"schema_name" text NOT NULL,
	"schema_version" text NOT NULL,
	"policy" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"prefill" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"events" jsonb DEFAULT '{}'::jsonb NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "restore_commands" (
	"id" text PRIMARY KEY NOT NULL,
	"vessel_id" uuid NOT NULL,
	"reason" text NOT NULL,
	"issued_by" text NOT NULL,
	"issued_at" timestamp with time zone NOT NULL,
	"fetched_at" timestamp with time zone,
	"applied_at" timestamp with time zone,
	"seq" bigserial NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "user_commands" (
	"id" text PRIMARY KEY NOT NULL,
	"vessel_id" uuid NOT NULL,
	"action" text NOT NULL,
	"username" text NOT NULL,
	"role" text DEFAULT '' NOT NULL,
	"temporary_password" text DEFAULT '' NOT NULL,
	"can_submit" boolean DEFAULT false NOT NULL,
	"active" boolean DEFAULT false NOT NULL,
	"issued_by" text NOT NULL,
	"issued_at" timestamp with time zone NOT NULL,
	"fetched_at" timestamp with time zone,
	"applied_at" timestamp with time zone,
	"seq" bigserial NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "api_keys" (
	"id" uuid PRIMARY KEY NOT NULL,
	"label" text NOT NULL,
	"token_hash" text NOT NULL,
	"token_lookup_hash" text NOT NULL,
	"group_id" text,
	"created_by" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"revoked_at" timestamp with time zone,
	"last_used_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "api_key_events" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "api_key_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"api_key_id" uuid NOT NULL,
	"kind" text NOT NULL,
	"at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "attachment_upload_chunks" (
	"content_hash" text NOT NULL,
	"chunk_index" integer NOT NULL,
	"received_at" timestamp with time zone NOT NULL,
	CONSTRAINT "attachment_upload_chunks_pkey" PRIMARY KEY("content_hash","chunk_index")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "notification_read_state" (
	"user_id" uuid NOT NULL,
	"notification_id" text NOT NULL,
	"read_at" timestamp with time zone NOT NULL,
	CONSTRAINT "notification_read_state_pkey" PRIMARY KEY("user_id","notification_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "outbox_receipts" (
	"vessel_id" uuid NOT NULL,
	"item_id" text NOT NULL,
	"sequence_no" bigint NOT NULL,
	"received_at" timestamp with time zone NOT NULL,
	CONSTRAINT "outbox_receipts_pkey" PRIMARY KEY("vessel_id","item_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "report_reviews" (
	"vessel_id" uuid NOT NULL,
	"report_id" text NOT NULL,
	"reviewed_by" text NOT NULL,
	"reviewed_at" timestamp with time zone NOT NULL,
	CONSTRAINT "report_reviews_pkey" PRIMARY KEY("vessel_id","report_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "vessel_users" (
	"vessel_id" uuid NOT NULL,
	"username" text NOT NULL,
	"role" text NOT NULL,
	"active" boolean NOT NULL,
	"can_submit" boolean NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"reported_at" timestamp with time zone NOT NULL,
	CONSTRAINT "vessel_users_pkey" PRIMARY KEY("vessel_id","username")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "report_versions" (
	"vessel_id" uuid NOT NULL,
	"report_id" text NOT NULL,
	"version_no" integer NOT NULL,
	"schema_kind" text NOT NULL,
	"schema_version" text DEFAULT '' NOT NULL,
	"event_type" text NOT NULL,
	"state" text NOT NULL,
	"event_time" timestamp with time zone NOT NULL,
	"fields" jsonb NOT NULL,
	"submitted_at" timestamp with time zone,
	"received_at" timestamp with time zone NOT NULL,
	CONSTRAINT "report_versions_pkey" PRIMARY KEY("vessel_id","report_id","version_no")
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "cadence_rules" ADD CONSTRAINT "cadence_rules_vessel_id_fkey" FOREIGN KEY ("vessel_id") REFERENCES "public"."vessels"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "regulatory_profile_assignments" ADD CONSTRAINT "regulatory_profile_assignments_vessel_id_fkey" FOREIGN KEY ("vessel_id") REFERENCES "public"."vessels"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "enrollments" ADD CONSTRAINT "enrollments_vessel_id_fkey" FOREIGN KEY ("vessel_id") REFERENCES "public"."vessels"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "rule_severity_assignments" ADD CONSTRAINT "rule_severity_assignments_vessel_id_fkey" FOREIGN KEY ("vessel_id") REFERENCES "public"."vessels"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "bundle_assignments" ADD CONSTRAINT "bundle_assignments_vessel_id_fkey" FOREIGN KEY ("vessel_id") REFERENCES "public"."vessels"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "bundle_assignments" ADD CONSTRAINT "bundle_assignments_bundle_id_fkey" FOREIGN KEY ("bundle_id") REFERENCES "public"."config_bundles"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "vessel_credentials" ADD CONSTRAINT "vessel_credentials_vessel_id_fkey" FOREIGN KEY ("vessel_id") REFERENCES "public"."vessels"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "vessel_sync_status" ADD CONSTRAINT "vessel_sync_status_vessel_id_fkey" FOREIGN KEY ("vessel_id") REFERENCES "public"."vessels"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "report_audit_events" ADD CONSTRAINT "report_audit_events_vessel_id_fkey" FOREIGN KEY ("vessel_id") REFERENCES "public"."vessels"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "invalidation_notices" ADD CONSTRAINT "invalidation_notices_vessel_id_fkey" FOREIGN KEY ("vessel_id") REFERENCES "public"."vessels"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "chat_messages" ADD CONSTRAINT "chat_messages_vessel_id_fkey" FOREIGN KEY ("vessel_id") REFERENCES "public"."vessels"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "remarks" ADD CONSTRAINT "remarks_vessel_id_fkey" FOREIGN KEY ("vessel_id") REFERENCES "public"."vessels"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "report_attachments" ADD CONSTRAINT "report_attachments_vessel_id_fkey" FOREIGN KEY ("vessel_id") REFERENCES "public"."vessels"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "field_policy_assignments" ADD CONSTRAINT "field_policy_assignments_vessel_id_fkey" FOREIGN KEY ("vessel_id") REFERENCES "public"."vessels"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "restore_commands" ADD CONSTRAINT "restore_commands_vessel_id_fkey" FOREIGN KEY ("vessel_id") REFERENCES "public"."vessels"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "user_commands" ADD CONSTRAINT "user_commands_vessel_id_fkey" FOREIGN KEY ("vessel_id") REFERENCES "public"."vessels"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "api_key_events" ADD CONSTRAINT "api_key_events_api_key_id_fkey" FOREIGN KEY ("api_key_id") REFERENCES "public"."api_keys"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "attachment_upload_chunks" ADD CONSTRAINT "attachment_upload_chunks_content_hash_fkey" FOREIGN KEY ("content_hash") REFERENCES "public"."attachment_uploads"("content_hash") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "notification_read_state" ADD CONSTRAINT "notification_read_state_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "outbox_receipts" ADD CONSTRAINT "outbox_receipts_vessel_id_fkey" FOREIGN KEY ("vessel_id") REFERENCES "public"."vessels"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "report_reviews" ADD CONSTRAINT "report_reviews_vessel_id_fkey" FOREIGN KEY ("vessel_id") REFERENCES "public"."vessels"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "vessel_users" ADD CONSTRAINT "vessel_users_vessel_id_fkey" FOREIGN KEY ("vessel_id") REFERENCES "public"."vessels"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "report_versions" ADD CONSTRAINT "report_versions_vessel_id_fkey" FOREIGN KEY ("vessel_id") REFERENCES "public"."vessels"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_vessels_groups" ON "vessels" USING gin ("groups");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "ux_cadence_rules_fleet" ON "cadence_rules" USING btree ("scope_type") WHERE (scope_type = 'fleet'::text);--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "ux_cadence_rules_group" ON "cadence_rules" USING btree ("group_tag") WHERE (scope_type = 'group'::text);--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "ux_cadence_rules_vessel" ON "cadence_rules" USING btree ("vessel_id") WHERE (scope_type = 'vessel'::text);--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "ux_reg_profile_assignments_fleet" ON "regulatory_profile_assignments" USING btree ("scope_type") WHERE (scope_type = 'fleet'::text);--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "ux_reg_profile_assignments_group" ON "regulatory_profile_assignments" USING btree ("group_tag") WHERE (scope_type = 'group'::text);--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "ux_reg_profile_assignments_vessel" ON "regulatory_profile_assignments" USING btree ("vessel_id") WHERE (scope_type = 'vessel'::text);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_schema_versions_cursor" ON "schema_versions" USING btree ("cursor");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ix_schema_versions_schema_name" ON "schema_versions" USING btree ("schema_name","published_at" DESC NULLS FIRST);--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "ux_rule_sev_assignments_fleet" ON "rule_severity_assignments" USING btree ("scope_type") WHERE (scope_type = 'fleet'::text);--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "ux_rule_sev_assignments_group" ON "rule_severity_assignments" USING btree ("group_tag") WHERE (scope_type = 'group'::text);--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "ux_rule_sev_assignments_vessel" ON "rule_severity_assignments" USING btree ("vessel_id") WHERE (scope_type = 'vessel'::text);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_config_bundles_cursor" ON "config_bundles" USING btree ("cursor");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ix_config_bundles_published_at" ON "config_bundles" USING btree ("published_at" DESC NULLS FIRST);--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "ux_bundle_assignments_fleet" ON "bundle_assignments" USING btree ("scope_type") WHERE (scope_type = 'fleet'::text);--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "ux_bundle_assignments_group" ON "bundle_assignments" USING btree ("group_tag") WHERE (scope_type = 'group'::text);--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "ux_bundle_assignments_vessel" ON "bundle_assignments" USING btree ("vessel_id") WHERE (scope_type = 'vessel'::text);--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "ux_vessel_credentials_lookup_hash" ON "vessel_credentials" USING btree ("token_lookup_hash");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_report_audit_events_report" ON "report_audit_events" USING btree ("vessel_id","report_id","occurred_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_invalidation_notices_vessel_seq" ON "invalidation_notices" USING btree ("vessel_id","seq");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_chat_messages_report" ON "chat_messages" USING btree ("vessel_id","report_id","sent_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_chat_messages_vessel_seq" ON "chat_messages" USING btree ("vessel_id","seq");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_remarks_report" ON "remarks" USING btree ("vessel_id","report_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_remarks_vessel_seq" ON "remarks" USING btree ("vessel_id","seq");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_report_attachments_report" ON "report_attachments" USING btree ("vessel_id","report_id","version_no");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "ux_field_policy_assignments_fleet" ON "field_policy_assignments" USING btree ("schema_name","schema_version") WHERE (scope_type = 'fleet'::text);--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "ux_field_policy_assignments_group" ON "field_policy_assignments" USING btree ("schema_name","schema_version","group_tag") WHERE (scope_type = 'group'::text);--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "ux_field_policy_assignments_vessel" ON "field_policy_assignments" USING btree ("schema_name","schema_version","vessel_id") WHERE (scope_type = 'vessel'::text);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_restore_commands_vessel_seq" ON "restore_commands" USING btree ("vessel_id","seq");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_user_commands_vessel_seq" ON "user_commands" USING btree ("vessel_id","seq");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "ux_api_keys_lookup_hash" ON "api_keys" USING btree ("token_lookup_hash");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ix_api_key_events_api_key_id" ON "api_key_events" USING btree ("api_key_id","at" DESC NULLS FIRST);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_outbox_receipts_vessel_sequence" ON "outbox_receipts" USING btree ("vessel_id","sequence_no");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_report_versions_vessel" ON "report_versions" USING btree ("vessel_id");
*/